//
//  UploadProgressPresenter.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 02/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UploadProgressPresentationLogic {
    func presentPhotos()
}

class UploadProgressPresenter: UploadProgressPresentationLogic {
    weak var viewController: UploadProgressDisplayLogic?
    func presentPhotos() {
        
    }
}
