//
//  PhotosListPresenter.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 31/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosListPresentationLogic {
    func presentPhotos(response: PhotosList.UploadPhotos.Response)
    func presentError(errorMsg: String)
}

class PhotosListPresenter: PhotosListPresentationLogic {
    weak var viewController: PhotosListDisplayLogic?
    
    func presentPhotos(response: PhotosList.UploadPhotos.Response) {
        let viewModel = PhotosList.UploadPhotos.ViewModel(info: response.info)
        viewController?.displayPhotos(viewModel: viewModel)
    }
    
    func presentError(errorMsg: String) {
        viewController?.displayErrorMessage(errorMsg: errorMsg)
    }
}
