//
//  PhotosListModels.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 31/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotosList
{
    // MARK: Use cases
    
    enum UploadPhotos {
        struct Request {
            var info: UploadPhotosRequest
        }
        struct Response {
            var info: UploadPhotosResponse
        }
        struct ViewModel {
            var info: UploadPhotosResponse
        }
    }
}
