//
//  PhotosListInteractor.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 31/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosListBusinessLogic {
    func getImagesAndUpload(request: PhotosList.UploadPhotos.Request)
}

protocol PhotosListDataStore {
}

class PhotosListInteractor: PhotosListBusinessLogic, PhotosListDataStore {
  var presenter: PhotosListPresentationLogic?
  var worker: PhotosListWorker?
  
  // MARK: Do something
    func getImagesAndUpload(request: PhotosList.UploadPhotos.Request) {
        worker = PhotosListWorker()
        worker?.uploadPhotos(request: request.info, onCompletion: { (success, response) in
            if success {
                if let response = response {
                    self.presenter?.presentPhotos(response: PhotosList.UploadPhotos.Response(info: response))
                }
            } else {
                self.presenter?.presentError(errorMsg: ErrorMsg.uploadErrorMsg)
            }
        })
    }
}
