//
//  PhotosListWorker.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 31/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Photos
import Cloudinary

class PhotosListWorker {
    func uploadPhotos(request: UploadPhotosRequest, onCompletion: @escaping (Bool, UploadPhotosResponse?) -> ()) {
        
        let config = CLDConfiguration(cloudName: CloudinaryKeys.cloudName, apiKey: CloudinaryKeys.apiKey)
        let cloudinary = CLDCloudinary(configuration: config)
        
        if let asset = request.asJson["image"] {
            let progressHandler = { (progress: Progress) in
                print("Uploading to Cloudinary: \(Int(progress.fractionCompleted * 100))%")
            }
            let imageObj = Image(image: asset, isUploaded: false)
            
            if let imgData = asset.pngData() {
                cloudinary.createUploader().upload(data: imgData, uploadPreset: CloudinaryKeys.preset, params: nil, progress: progressHandler) { (result, error) in
                    if let error = error {
                        print("\(ErrorMsg.uploadErrorMsg)", error)
                    } else {
                        if let result = result {
                            print("\(SuccessMsg.successErrorMsg)", result.resultJson)
                        }
                    }
                }
            }
            onCompletion(true, UploadPhotosResponse(photos: imageObj))
        }
    }
}
