//
//  PhotosListWorkerTests.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 06/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MarkkAssignment_PrachiGade
import XCTest

class PhotosListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PhotosListWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPhotosListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPhotosListWorker()
  {
    sut = PhotosListWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
