//
//  PhotosListPresenterTests.swift
//  MarkkAssignment_PrachiGade
//
//  Created by Prachi Gade on 06/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MarkkAssignment_PrachiGade
import XCTest

class PhotosListPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PhotosListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()   {
        super.setUp()
        setupPhotosListPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPhotosListPresenter() {
        sut = PhotosListPresenter()
    }
    
    // MARK: Test doubles
    
    class PhotosListDisplayLogicSpy: PhotosListDisplayLogic {
        var displayPhotosCalled = false
        
        func displayPhotos(viewModel: PhotosList.UploadPhotos.ViewModel) {
            displayPhotosCalled = true
        }
        
        func displayErrorMessage(errorMsg: String) {
            
        }
    }
    
    // MARK: Tests
    func testDisplayPhotos() {
        let spy = PhotosListDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.presentPhotos(response: PhotosList.UploadPhotos.Response(info: UploadPhotosResponse(photos: Image(image: nil, isUploaded: nil))))
        
        // Then
        XCTAssertTrue(spy.displayPhotosCalled, "present photos(response:) should ask the view controller to display the result")
    }
}
